# -*- coding: utf-8 -*-
"""pandas exercise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zUpyZN_dv1Hf40lmqhS2JKiRvh43QLr9
"""

import pandas as pd
import numpy as np

"""Write a Pandas program to count of occurrence of a specified substring in a DataFrame column?"""

df = pd.DataFrame({
    'name_code': ['c001','c002','c022', 'c2002', 'c2222'],
    'date_of_birth ': ['12/05/2002','16/02/1999','25/09/1998','12/02/2022','15/09/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})

print("Original DataFrame:")
print(df)
print("\nCount occurrence of 2 in date_of_birth column:")
df['count'] = list(map(lambda x: x.count("2"), df['name_code']))
print(df)

# df['count'] = list(map(lambda x: x.count("2"), df['name_code']))
# df
# shortcut way

"""Write a Pandas program to check whether alphabetic values present in a given column of a DataFrame?"""

df = pd.DataFrame({
    'company_code': ['Company','Company a001','Company 123', 'abcd', 'Company 12'],
    'date_of_sale': ['12/05/2002','16/02/1999','25/09/1998','12/02/2022','15/09/1997'],
    'sale_amount': [12348.5, 233331.2, 22.5, 2566552.0, 23.0]})

df['company_code_is_alpha'] = list(map(lambda x: x.isalpha(), df['company_code']))

print("Original DataFrame:")
print(df)
print("\nWhether Alphabetic values present in company_code column?")
df['company_code_is_alpha'] = list(map(lambda x: x.isalpha(), df['company_code']))
print(df)

# df['company_code_is_alpha'] = list(map(lambda x: x.isalpha(), df['company_code']))
# dfway
# shortcut