# -*- coding: utf-8 -*-
"""Python Assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aoQnZSFMcMW_pzQOf-_6Cn0hgOxSf1Iz
"""

# 1. p,s=9,8
# p=p*s
print(9*8)
# p-=s
print(72-8)

# p=p/s
print(64/8)

# p>>=s
print(8>>8)

#p=p<<s
print(0<<8)

# 2.Example of a multiple comment?
'''this is an example 
of multiline comment'''
print('raz')

#3. S,t = 3,4

#S%=t
print(3%4)

# 4. A,B=8,10
#A&B
print(8&10)

#AorB
print(8|10)

# 5. command to find the lentgh string?
a = 'india'
print(len(a))

# 6. Which of the following is an invalid identifiers?
#a = a123
#b = 123
#c = _9_c
#d = aB1!
# option d is invalid because it consists operator(!).

# 7. Giive an example for each these for a  4 word sentence-
a ='what is your name'
#Title case
'What Is Your Name'
# snake case
'what_is_your_name'
#camel case
'what Is Your Name'

# 8. what is the output for b*(c+a).
# a,b,c = 1,2,3
print(2*(3+1))

# 9.In given string print 'are' only.
a = 'how are you'
print(a[4:7])

# 10.Write the command to get the imaginary number in the code below.
x= 5
y =5
z=complex(x,y)
print(z-5)

# 11.bool({})?
#      bool({false})
# true

# 12.What are the data types of following respectively?
a = (1,[2,3])
print(type(a))
b = [1,2,'f']
print(type(b))
c = 'hey1'
print(type(c))
d = 123
print(type(d)) 
e = {(1,2):['e']}
print(type(e))

# 13. What is the output of code below?
print(10==9)

# 14. What is the output of code below?
quantity = 3
item = 567
price = 49.95
myorder ='i want to {2} dollars for {0} pieces of item {1}'
print(myorder.format(3,5,9))

# 15.Convert the words 'miss' and 'python' to 'mam' and 'C' respectively without redeclaring the string?
a = 'hey miss! Welcome  to python'
print(a.replace('miss','mam').replace('python','c'))

# 16. Convert the string to tilte case and lower case?
a = 'HYderabaD'
print(a.lower())
print(a.title())

# 17. Print how many numbers of 'A'/'a' are there in string without counting manually?
x = 'All apples are red in clor and round in shape'
x.count('A')
x.count('a')

# 18. What is the output of code below?
x = {1,2,3,4,5}
y = {4,5,6,7,8}
x.update(y)
print(x)

# 19. What is the output of code below?
x = {1,2,3,4,5}
y = {4,5,6,7,9}
# print(x|y)
z = x.union(y)
print(z)

# 20. What are the outputs of code below?
print(0|True)
print(0==True)
print('19'==19)

# 21. Write python programm to add first n numbers?
a = int(input('enter a number'))
sum = 0
for i in range(1,a+1):
   sum = sum +i
print(sum)

# 22.Write a code to loop over the items in fruits list?
fruits = ["apple","orange","kiwi"] 
i=0
while i in range(len(fruits)):
  print(fruits[i])
  i+=1

# 23. Write a python code to print 6 tables using for and while loop?
# while loop
i=1
while (i<=10):
   print(6,'x',i,'=',6*i)
   i+=1
# for loop
for i in range(1,11):
   print(6,'x',i,'=',6*i)

# 24. Write a command to get the value of this 6**4
a = 6**4
print(a)

# 25. What are the outputs for the code below?
for x in [1,2,3]:
  print(x-1)

# 26. What is the output of the print tuple[0] if tuple=('abcd',786,2.23,'john',70.2)?
tuple=('abcd',786,2.23,'john',70.2)
print(tuple[0])

# 27. What is the output of L[-2] if L =[1,2,3]?
L = [1,2,3]
(L[-2])

# 28. What will be the output of  below given code?
colors = ['white','Black','Grey']
x = 'Red'!=colors
print(x)

# 29. Which is mutable and immutable in list and tuple?
#list
a = [1,23,4,'abc',8]
a[2]='AA'
a
#list is mutable

#tuple
a = (1,23,4,'abc',8)
a[2]='AA'
a
#tuple does not support item assignment. So it is immutable

# 30. What is the output of tiny*3, if tiny =[123, 'john']?
tiny = [123,'john']
print(tiny*3)

# 31. Which is the function to check in a string that all characters are alphanumeric?
a ='abc123'
(a.isalnum())

# 32. What is the command line to get the output as heshewe?
a = ['he','she','we']
print(''.join(a))

# 33. What is the position of number 3? 
L = [1,2,2,[2,3],5]
print(L[3][1])

# 34. Calculate the total number of 9 in below-given list? And state the predefined function to calculate the number of '9's?
List1 = [9,90,99,999,9999]
A =str(List1)
A.count('9')

# 35. What is the result of this code?
nums = [10,9,8,7,6,5]
nums[0] = nums[1] - 5  # 10 = 9 - 5 = 4 
if 4 in nums: 
  print(nums[3])  
else:
  print(nums[4])

# 36. What is the result of this code?
nums = [9,8,7,6,5]
nums.append(4)
nums.insert(2,11)
print(len(nums))

# 37. What is the result of this code?
list = [1,1,2,3,5,8,13]
print(list[list[4]])  #repitition doesn't allows in list

# 38. Which of the following is a false statement in python?
int(144)==144
int('144')==144
int(144.0)==144

# 39. What is the output of[1,2,3]+[4,5,6]?
a = [1,2,3]
b = [4,5,6]
print(a+b)

# 40. What is the command to sort a list?
a = [1,3,6,5,2,4]
(a.sort())
print(a)

# 41. Which of the following statements is used when a statement is required syntactically but you do not want any command or code to execute?
# a. break
# b. continue
# c. pass
# d. None of the above.
# pass
if 1:
  pass

# 42. What is the result of this code?
tup = ('hi','python',2)
print(type(tup))
print(tup)
print(tup[1:])
print(tup[0:1])
print(tup+tup)
print(tup*3)
# print(tup[2]='hi')  #tuple does not support item assingment.
# print(tup)

# 43. What is the result of this code?
for i in range(0,5):
  print(i)
  break

# 44. What is the result of this code?
for x in range(21,5,-3):
  print(x)

# 45. program to check wheather a number is even or not.
a = int(input('enter a number'))
if ((a%2)==0):
  print('even')
else:
    print('odd')

# 46. Bring this output using loops.
for i in range(1,6):
  print('*'*i)

# 47. Write a Python programm to get the Python version you are using?
import sys
print('python version')
print(sys.version)
print('version info')
print(sys.version_info)

# 48. Write a Python programm to find prime numbers within a given interval?
a = int(input(' enter start value'))
b = int(input(' enter end value'))
print("Prime numbers between",a, "and",b, "are:")
for val in range(a,b):
  if val > 1:
    for i in range(2, val):
      if (val % i) == 0:
        break
    else:
      print(val, end=" ")

# 48.
a = int(input('enter a number'))
if (( a == 0 ) or ( a == 1 )):
  print('niether prime nor composite')
elif(a>1):
  for i in range(2,a):
    if (a%i == 0):
       print('it is composite number')
       break
  else:
      print('it is a prime number')

# 49. Find the cube root of a number in python programming?
a = int(input('enter a number'))
print(a**(1/3))



# 50. Write a Python a programm that will accept the base and height of triangle and compute the area?
a = int(input('enter base of triangle'))
b = int(input('enter a height of triangle'))
print(1/2*a*b)

# 51. Write a Python a programm to solve (x+y)*(x+y)?
x = int(input('enter a number'))
y = int(input('enter a number'))
print((x+y)*(x+y))

# 52. Write a Python a programm to calculate the sum of three given numbers, if the values are equal then return thrice of their sum?
a = int(input('enter a number'))
b = int(input('enter a number'))
c = int(input('enter a number'))
sum = a+b+c
if (a==b==c):
  print(sum*3)
else:
    print(sum)

# 53. Write a Python a programm to compute the distance between the given points (x1,y1) and (x2,y2)?
x1=float(input('enter the value'))
x2=float(input('enter the value'))
y1=float(input('enter the value'))
y2=float(input('enter the value'))
print(((x2 - x1)**2 +(y2 - y1)**2)**0.5)

# 54. Write a python program to calculate body mass index?
a = float(input('enter your height in Feet'))
b = float(input('enter your weight in Kilogram'))
c = b/(a*a)

print('Your body mass index is',c)

# 55. Write a python program to filter the positive numbers from a list?
a = [1,3,-7,-5,4,2]
positive_numbers = [number for number in a if number >= 0]
print(positive_numbers)

# 56.Write a python program to test if a variable is a list or tuple or a set?
a =(1,'abc',3.6,7)
a =[1,'abc',3.6,7]
a ={1,'abc',3.6,7}
if type(a) is list:
    print('a is a list')
elif type(a) is set:
    print('a is a set')
elif type(a) is tuple:
    print('a is a tuple')    
else:
    print('Neither a list or a set or a tuple.')

# 57. Write a python program to check if a number is positive,negative or zero?
a = int(input('enter a number'))
if (a==0):
  print('zero')
elif(a<0):
    print('negative number')
else:
      print('positive number')

# 58. Write a program to test whether a passed letter is vowel or not?
l = input("Enter the character: ")
if l.lower() in ('a', 'e', 'i', 'o', 'u'):
  print('Vowel')
elif l.upper() in ('A', 'E', 'I', 'O', 'U'):
  print('Vowel')
else:
  print('Consonant')

# 59. Write a Python programm to display the multiplication table of a given number?
a = int(input('Enter the number to print the table: '))
i=0
while (i<=10):
  print(a,'x',i,'=',a*i)
  i+=1

# 60. Wirte a Python Program to add two matrices using loops?

a = [[1,7,3],
    [4 ,5,6],
    [7 ,8,9]]

b = [[5,8,1],
    [2,7,3],
    [4,5,9]]

add = [[0,0,0],
       [0,0,0],
       [0,0,0]]

# iterate through rows
for i in range(len(a)):
   # iterate through columns
   for j in range(len(a[0])):
       add[i][j] = a[i][j] + b[i][j]

for r in add:
   print(r)